### ISSUE TITLE
PRs based on reference will fail CI due to unavailable SHA

### ISSUE THREAD

**Issue by juliandescottes** [ochameau/ff-dt#22]
Right now, the reference branch still has `fa2c77e70b7aea552c3322e7000c156afcc03a51 ` in bin/deps/firefox/mozilla-central/artifacts instead of `dad9a0a2c232578a873279156b99ff8d758fb962 ` on master. This tag is not available on https://github.com/ochameau/ff-dt-artifacts/tags/ and all CI for PRs based on reference will therefore fail.

Can we just update reference here?

**Comment by ochameau** [comment]
Yes!
The easiest is to do:
```
git fetch origin
git checkout origin/master
git push HEAD:reference -f
```
Any in-progress pull requests/branches should just be rebased.
If rebase fails, the easiet is to cherry pick on top of the new origin/reference.

I've been updating reference like this every now and then.

**Comment by ochameau** [comment]
`reference` just updated.
