### ISSUE TITLE
Error running ./run with clean checkout

### ISSUE THREAD

**Issue by bgrins** [ochameau/ff-dt#6]
Following the readme: https://github.com/ochameau/ff-dt#get-the-sources

```
> git clone git@github.com:ochameau/ff-dt.git
> cd ff-dt/
> ./run
grep: /proc/version: No such file or directory
PLATFORM=macosx64-opt
firefox-branch=mozilla-central
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by ochameau** [comment]
Today's updates should fix all that. Please test it again, you may have to do `rm -rf bin/artifacts/`.
Sorry for not having looked at Mac support until yesterday...

**Comment by bgrins** [comment]
Fixed now
